name: DevSecOps Pipeline for React.js Frontend

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Run Tests and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      - name: Ensure jest-dom is installed
        run: npm install --save-dev @testing-library/jest-dom --force

      - name: Smoke Test (unit tests)
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Lint Check
        run: npm run lint || true

  docker-build-and-test:
    name: Docker Build and SCUBA Test
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t react-app:${{ github.sha }} .

      - name: Run container for smoke test
        run: |
          docker run -d -p 3000:80 --name testcontainer react-app:${{ github.sha }}
          sleep 10
          curl -f http://localhost:3000 || (docker logs testcontainer && exit 1)
          docker stop testcontainer
          docker rm testcontainer

  docker-push:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    needs: docker-build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }}
